// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLTest01_WebApp
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Timestamp")]
            public DateTime Timestamp { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"CableLength")]
            public float CableLength { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"CableWeightMeter")]
            public float CableWeightMeter { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"CableRadius")]
            public float CableRadius { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"CableVolumeMeter")]
            public float CableVolumeMeter { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"WaterDensity")]
            public float WaterDensity { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Gravity")]
            public float Gravity { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"PayloadWeight")]
            public float PayloadWeight { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"PayloadVolume")]
            public float PayloadVolume { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"WinchRadius")]
            public float WinchRadius { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"WinchWeight")]
            public float WinchWeight { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"WinchFriction")]
            public float WinchFriction { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"CableLengthOnWinch")]
            public float CableLengthOnWinch { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"CableLengthInWater")]
            public float CableLengthInWater { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"CableSpeed")]
            public float CableSpeed { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"CableAcceleration")]
            public float CableAcceleration { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"WinchAngularSpeed")]
            public float WinchAngularSpeed { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"WinchAngularAcceleration")]
            public float WinchAngularAcceleration { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"MotorTorque")]
            public float MotorTorque { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Timestamp")]
            public float Timestamp { get; set; }

            [ColumnName(@"CableLength")]
            public float CableLength { get; set; }

            [ColumnName(@"CableWeightMeter")]
            public float CableWeightMeter { get; set; }

            [ColumnName(@"CableRadius")]
            public float CableRadius { get; set; }

            [ColumnName(@"CableVolumeMeter")]
            public float CableVolumeMeter { get; set; }

            [ColumnName(@"WaterDensity")]
            public float WaterDensity { get; set; }

            [ColumnName(@"Gravity")]
            public float Gravity { get; set; }

            [ColumnName(@"PayloadWeight")]
            public float PayloadWeight { get; set; }

            [ColumnName(@"PayloadVolume")]
            public float PayloadVolume { get; set; }

            [ColumnName(@"WinchRadius")]
            public float WinchRadius { get; set; }

            [ColumnName(@"WinchWeight")]
            public float WinchWeight { get; set; }

            [ColumnName(@"WinchFriction")]
            public float WinchFriction { get; set; }

            [ColumnName(@"CableLengthOnWinch")]
            public float CableLengthOnWinch { get; set; }

            [ColumnName(@"CableLengthInWater")]
            public float CableLengthInWater { get; set; }

            [ColumnName(@"CableSpeed")]
            public float CableSpeed { get; set; }

            [ColumnName(@"CableAcceleration")]
            public float CableAcceleration { get; set; }

            [ColumnName(@"WinchAngularSpeed")]
            public float WinchAngularSpeed { get; set; }

            [ColumnName(@"WinchAngularAcceleration")]
            public float WinchAngularAcceleration { get; set; }

            [ColumnName(@"MotorTorque")]
            public float MotorTorque { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
