// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;

namespace MLModel_ConsoleApp1
{
    public partial class MLModel
    {
        public const string RetrainFilePath =  @"D:\source\visual-studio\NET10\MLTest01\MLTest01.WebApp\Data\input.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"CableLength", @"CableLength"),new InputOutputColumnPair(@"CableWeightMeter", @"CableWeightMeter"),new InputOutputColumnPair(@"CableRadius", @"CableRadius"),new InputOutputColumnPair(@"CableVolumeMeter", @"CableVolumeMeter"),new InputOutputColumnPair(@"WaterDensity", @"WaterDensity"),new InputOutputColumnPair(@"Gravity", @"Gravity"),new InputOutputColumnPair(@"PayloadWeight", @"PayloadWeight"),new InputOutputColumnPair(@"PayloadVolume", @"PayloadVolume"),new InputOutputColumnPair(@"WinchRadius", @"WinchRadius"),new InputOutputColumnPair(@"WinchWeight", @"WinchWeight"),new InputOutputColumnPair(@"WinchFriction", @"WinchFriction"),new InputOutputColumnPair(@"CableLengthOnWinch", @"CableLengthOnWinch"),new InputOutputColumnPair(@"CableLengthInWater", @"CableLengthInWater"),new InputOutputColumnPair(@"CableSpeed", @"CableSpeed"),new InputOutputColumnPair(@"CableAcceleration", @"CableAcceleration"),new InputOutputColumnPair(@"WinchAngularSpeed", @"WinchAngularSpeed"),new InputOutputColumnPair(@"WinchAngularAcceleration", @"WinchAngularAcceleration")})      
                                    .Append(mlContext.Transforms.Conversion.ConvertType(@"Timestamp", @"Timestamp"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"CableLength",@"CableWeightMeter",@"CableRadius",@"CableVolumeMeter",@"WaterDensity",@"Gravity",@"PayloadWeight",@"PayloadVolume",@"WinchRadius",@"WinchWeight",@"WinchFriction",@"CableLengthOnWinch",@"CableLengthInWater",@"CableSpeed",@"CableAcceleration",@"WinchAngularSpeed",@"WinchAngularAcceleration",@"Timestamp"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=4,NumberOfIterations=2135,MinimumExampleCountPerLeaf=20,LearningRate=0.18695989042799877,LabelColumnName=@"MotorTorque",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.9999997766729865,FeatureFraction=0.99999999,L1Regularization=2E-10,L2Regularization=0.3179966009523822},MaximumBinCountPerFeature=347}));

            return pipeline;
        }
    }
 }
