
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    CableLength = 2000F,
    CableWeightMeter = 10F,
    CableRadius = 25F,
    CableVolumeMeter = 19634956F,
    WaterDensity = 1025F,
    Gravity = 981F,
    PayloadWeight = 20000F,
    PayloadVolume = 20F,
    WinchRadius = 8F,
    WinchWeight = 1000F,
    WinchFriction = 0F,
    CableLengthOnWinch = 19999516F,
    CableLengthInWater = 4839693F,
    CableSpeed = 69567900F,
    CableAcceleration = 1F,
    WinchAngularSpeed = 1F,
    WinchAngularAcceleration = 125F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual MotorTorque with predicted MotorTorque from sample data...\n\n");


Console.WriteLine($"CableLength: {2000F}");
Console.WriteLine($"CableWeightMeter: {10F}");
Console.WriteLine($"CableRadius: {25F}");
Console.WriteLine($"CableVolumeMeter: {19634956F}");
Console.WriteLine($"WaterDensity: {1025F}");
Console.WriteLine($"Gravity: {981F}");
Console.WriteLine($"PayloadWeight: {20000F}");
Console.WriteLine($"PayloadVolume: {20F}");
Console.WriteLine($"WinchRadius: {8F}");
Console.WriteLine($"WinchWeight: {1000F}");
Console.WriteLine($"WinchFriction: {0F}");
Console.WriteLine($"CableLengthOnWinch: {19999516F}");
Console.WriteLine($"CableLengthInWater: {4839693F}");
Console.WriteLine($"CableSpeed: {69567900F}");
Console.WriteLine($"CableAcceleration: {1F}");
Console.WriteLine($"WinchAngularSpeed: {1F}");
Console.WriteLine($"WinchAngularAcceleration: {125F}");
Console.WriteLine($"MotorTorque: {-67609944F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted MotorTorque: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

